### ISSUE TITLE
Why aren't these part of the main repository?

### ISSUE THREAD

**Issue by Bilge** [kubawerlos/php-cs-fixer-custom-fixers#128]
Most of these should be part of the upstream repository as they should be useful to most projects. Why are they not being accepted/submitted upstream? Referring to fixers with names like `PhpCsFixerCustomFixers\Fixer\NoLeadingSlashInGlobalNamespaceFixer::name()` is quite noisy. Also there doesn't seem to be any way to batch include all of them.

**Comment by kubawerlos** [comment]
Some already are - like `implode_call` or `phpdoc_var_annotation_correct_order`.

Some are in PR - like [OperatorLinebreakFixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4021) or [SingleLineThrowFixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4452).

The reason is that fixers here are released much faster (like the 2 for data providers - took a week from idea to release - not possible on the main repository), but at the cost of potential bugs - of course I do my best - think heavily about test cases and test it on many projects and repositories - but still -review on the main repository can improve the quality even more.

Usually when someone asks I make a PR to main repository - did you mentioned `NoLeadingSlashInGlobalNamespaceFixer` as a random example or would you like to see it in PR to the Fixer?

And lastly, to include all of them you can use [this](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/blob/v1.15.1/.php_cs.dist#L147) trick.

**Comment by Bilge** [comment]
It *was* a random example, but is also one I would particularly like to see go mainstream, which shouldn't be that surprising since I feel that way about most of them.

**Comment by kubawerlos** [comment]
If you think any of the fixers deserves moving to PHP CS Fixer I think best way would be to create an issue there and if marked as a feature then I'll create PR.
