### ISSUE TITLE
Don't allow use of empty()

### ISSUE THREAD

**Issue by weshooper** [kubawerlos/php-cs-fixer-custom-fixers#330]
It helps make the intention clearer as you instantly know the type of the variable without needing to guess or look it up. Based on related discussion at https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4087, a fixer would be a nice fit here perhaps? i.e. swap to `mb_strlen()` if a string, `count()` if an array.

**Comment by mvorisek** [comment]
but to what to replace to?

**Comment by weshooper** [comment]
@mvorisek good question! I can only think of the simple replacements mentioned above from experience going through updating existing code. But thinking about it a bit more now, knowing the replacement relies on knowing what the variable type is - and I've no idea whether PHP CS Fixer can determine that?

There's also an edge case we ran into when converting `empty()` usage, if the variable doesn't exist (since `empty()` also checks `isset()`, as discussed in the PR above) which meant replacements were a little more complex.

**Comment by kubawerlos** [comment]
It is possible to determine only some of the variables used in `empty`, but not all, and for those, it would have be changed as official [docs](https://www.php.net/manual/en/function.empty.php) says:

> **empty()** is essentially the concise equivalent to **!isset($var) || $var == false**.

And that definitely wouldn't not be fixing the code.

PHPStan's extension [phpstan/phpstan-strict-rules](https://github.com/phpstan/phpstan-strict-rules) disallows `empty` and I would recommend it to use instead of "fixing" `empty` automagically.
